
TEXTS = {
    'tr': {
        # Sidebar & Main
        "app_title": "FC26 Kadro Optimize Edici",
        "nav_title": "Navigasyon",
        "page_select": "Sayfa Seçin:",
        "home": "Ana Sayfa",
        "data_analysis": "Veri Analizi",
        "ml_training": "Makine Öğrenmesi",
        "synergy_nn": "Sinerji NN",
        "optimization": "Takım Optimizasyonu",
        "about": "Hakkında",
        "data_status_loaded": "Veri Yüklendi",
        "total_players": "Toplam Oyuncu",
        "avg_overall": "Ort. Overall",
        "data_status_unloaded": "Veri yüklenmedi",
        "load_data_button": "Veri Yükle",
        "model_status": "Model Durumu",
        "ml_model": "ML Modeli",
        "synergy_model": "Sinerji Modeli",
        "made_with": "Streamlit ile yapıldı",
        "version": "Sürüm",
        "error_file_not_found": "HATA: '{path}' dosyası bulunamadı!",
        "info_save_csv": "Lütfen CSV dosyanızı '{path}' olarak kaydedin.",
        "spinner_loading_data": "Veri yükleniyor...",
        "warning_load_data_first": "Önce veri yüklemeniz gerekiyor!",

        # Home Page
        "home_quick_start": "Hızlı Başlangıç",
        "home_start_prompt": "Sol menüden **'Veri Yükle'** butonuna basarak başlayın!",
        "home_data_loaded_prompt": "Veri yüklendi! Sol menüden bir sayfa seçerek devam edin.",
        "home_avg_value": "Ortalama Değer",
        "home_max_overall": "En Yüksek Overall",
        "home_saved_models": "Kayıtlı Modeller",
        "home_models_found": "{count} adet eğitilmiş model bulundu.",
        "home_view_models": "Modelleri Görüntüle",
        "home_no_models": "Henüz eğitilmiş model yok.",
        "home_recent_squads": "Son Oluşturulan Takımlar",
        "home_squads_found": "{count} adet takım kaydı bulundu.",
        "home_view_squads": "Takımları Görüntüle",
        "home_no_squads": "Henüz oluşturulmuş takım yok.",

        # Data Analysis Page
        "da_title": "Veri Analizi ve Görselleştirme",
        "da_filters": "Filtreler",
        "da_min_overall": "Minimum Overall",
        "da_max_value": "Max Değer (EUR)",
        "da_position_filter": "Pozisyon Filtresi",
        "da_showing_players": "{count} oyuncu gösteriliyor (Toplam: {total})",
        "da_tab_distributions": "Dağılımlar",
        "da_tab_value": "Değer Analizi",
        "da_tab_nationality": "Milliyet/Lig",
        "da_tab_player_list": "Oyuncu Listesi",
        "da_chart_overall_dist": "Overall Dağılımı",
        "da_chart_age_dist": "Yaş Dağılımı",
        "da_chart_overall_vs_value": "Overall vs Değer İlişkisi",
        "da_chart_top_10_valuable": "En Değerli 10 Oyuncu",
        "da_chart_top_15_nations": "En Çok Oyuncu Olan 15 Ülke",
        "da_chart_top_10_leagues": "En Çok Oyuncu Olan 10 Lig",
        "da_player_list_info": "Filtreyle eşleşen toplam {count} oyuncu listeleniyor.",

        # ML Page
        "ml_title": "Makine Öğrenmesi Model Eğitimi",
        "ml_info": "Makine öğrenmesi modelleri, oyuncu değerlerini tahmin ederek düşük değerli ama potansiyeli yüksek oyuncuları bulmanıza yardımcı olur.",
        "ml_tab_train": "Model Eğitimi",
        "ml_tab_compare": "Model Karşılaştırma",
        "ml_tab_undervalued": "Değeri Düşük Oyuncular",
        "ml_train_new": "Yeni Model Eğit",
        "ml_model_features_title": "Model Özellikleri:",
        "ml_model_feature_1": "- Random Forest (100 ağaç)",
        "ml_model_feature_2": "- Gradient Boosting (100 ağaç)",
        "ml_model_feature_3": "- XGBoost (100 ağaç)",
        "ml_model_feature_4": "- R², MAE, RMSE metrikleri",
        "ml_model_feature_5": "- En iyi model otomatik seçilir",
        "ml_test_data_ratio": "Test Veri Oranı",
        "ml_training_data": "Eğitim Verisi",
        "ml_test_data": "Test Verisi",
        "ml_button_start_training": "Model Eğitimini Başlat",
        "ml_spinner_training": "Modeller eğitiliyor... Bu birkaç dakika sürebilir.",
        "ml_success_trained": "Modeller başarıyla eğitildi!",
        "ml_performance": "Model Performansı",
        "ml_r2_score": "R² Skoru",
        "ml_mae": "MAE",
        "ml_rmse": "RMSE",
        "ml_button_save_model": "Modeli Kaydet",
        "ml_success_saved": "Model kaydedildi: {path}",
        "ml_error_training": "Model eğitimi sırasında bir hata oluştu: {e}",
        "ml_info_train_first": "Önce 'Model Eğitimi' sekmesinden bir model eğitmeniz gerekiyor.",
        "ml_chart_r2_comparison": "R² Skoru Karşılaştırması",
        "ml_chart_mae_comparison": "MAE Karşılaştırması (Milyon EUR)",
        "ml_undervalued_threshold": "Değer Düşüklüğü Eşiği",
        "ml_undervalued_help": "Model tahmini / gerçek değer oranı. Örn: 0.5 = gerçek değer tahminin yarısı.",
        "ml_button_find_undervalued": "Değeri Düşük Oyuncuları Bul",
        "ml_spinner_finding": "Analiz ediliyor...",
        "ml_undervalued_found": "{count} değeri düşük oyuncu bulundu!",
        "ml_undervalued_not_found": "Belirtilen eşikte değeri düşük oyuncu bulunamadı. Eşiği artırın.",
        "ml_undervalued_info_showing": "İlk 50 oyuncu gösteriliyor. Toplam: {count}",
        "ml_undervalued_avg_overall": "Ortalama Overall",
        "ml_undervalued_avg_age": "Ortalama Yaş",
        "ml_undervalued_avg_potential": "Ortalama Potansiyel",
        "ml_undervalued_df_cols": {'short_name': 'Oyuncu', 'overall': 'OVR', 'potential': 'POT', 'age': 'Yaş', 'player_positions': 'Pozisyon', 'actual_value': 'Gerçek Değer', 'predicted_value': 'Tahmin', 'value_diff': 'Fark', 'value_ratio': 'Oran', 'club_name': 'Kulüp', 'league_name': 'Lig', 'nationality_name': 'Ülke'},
        "ml_hyperparameters": "Hiperparametre Ayarları (İsteğe Bağlı)",
        "ml_n_estimators": "Ağaç Sayısı",
        "ml_max_depth": "Maksimum Derinlik (0 = Sınırsız)",
        "ml_learning_rate": "Öğrenme Oranı",
        "ml_rf_settings": "Random Forest Ayarları",
        "ml_gb_settings": "Gradient Boosting Ayarları",
        "ml_xgb_settings": "XGBoost Ayarları",

        # Synergy Page
        "syn_title": "Sinerji Neural Network Eğitimi",
        "syn_info": "Sinerji NN, 11 oyuncunun birlikte nasıl oynayacağını tahmin eder. Yaş dengesi, oyun stili uyumu, kimya gibi 28+ özelliği analiz eder.",
        "syn_model_ready": "Sinerji modeli yüklü ve kullanıma hazır!",
        "syn_model_overwrite_info": "Yeni bir model eğitirseniz, mevcut modelin üzerine yazılacaktır.",
        "syn_model_not_ready": "Henüz eğitilmiş bir sinerji modeli yok.",
        "syn_model_details_title": "Model Bilgileri:",
        "syn_model_detail_1": "- 3 katmanlı Sinir Ağı (NN)",
        "syn_model_detail_2": "- 128-64-32 nöron yapısı",
        "syn_model_detail_3": "- 28+ takım özelliği analizi",
        "syn_model_detail_4": "- Sinerji skoru çıktısı (0-100)",
        "syn_tab_train": "Model Eğitimi",
        "syn_tab_test": "Model Testi",
        "syn_train_new": "Yeni Sinerji NN Eğit",
        "syn_training_samples": "Eğitim Örnek Sayısı",
        "syn_samples_help": "Daha fazla örnek = daha iyi model ama daha uzun eğitim süresi.",
        "syn_button_start_training": "Sinerji NN Eğitimini Başlat",
        "syn_spinner_creating_predictor": "Sinerji tahmincisi oluşturuluyor...",
        "syn_spinner_training": "{count} sentetik takım oluşturuluyor ve model eğitiliyor...",
        "syn_spinner_saving": "Model kaydediliyor...",
        "syn_success_trained": "Sinerji NN başarıyla eğitildi ve kaydedildi!",
        "syn_model_saved_at": "Model kaydedildi: {path}",
        "syn_training_results": "Eğitim Sonuçları",
        "syn_train_mse": "Eğitim MSE",
        "syn_test_mse": "Test MSE",
        "syn_train_r2": "Eğitim R²",
        "syn_test_r2": "Test R²",
        "syn_perf_excellent": "Mükemmel model performansı! Model çok iyi öğrendi.",
        "syn_perf_good": "İyi model performansı. Model başarılı.",
        "syn_perf_fair": "Orta model performansı. Daha fazla örnekle eğitmeyi deneyebilirsiniz.",
        "syn_perf_poor": "Düşük model performansı. Parametreleri veya örnek sayısını gözden geçirin.",
        "syn_test_info": "Rastgele bir takım oluşturup mevcut sinerji modelini test edin.",
        "syn_test_formation": "Test Formasyonu",
        "syn_button_test": "Rastgele Takım Oluştur ve Test Et",
        "syn_test_results_title": "Test Takımı Sonuçları",
        "syn_test_score": "Sinerji Skoru",
        "syn_test_avg_overall": "Ort. Overall",
        "syn_test_avg_age": "Ort. Yaş",
        "syn_test_total_value": "Toplam Değer",
        "syn_test_squad_list": "Test Takımı Kadrosu",
        "syn_error_not_enough_players": "Test takımı oluşturulamadı. Veri setinde yeterli oyuncu olmayabilir.",
        "syn_hyperparameters": "Hiperparametre Ayarları",
        "syn_hidden_layers": "Gizli Katman Yapısı (örn: 128,64,32)",
        "syn_hidden_layers_help": "Her katmandaki nöron sayısını virgülle ayırarak girin.",
        "syn_activation": "Aktivasyon Fonksiyonu",
        "syn_solver": "Çözücü (Optimizer)",
        "syn_max_iter": "Maksimum İterasyon (Epoch)",
        
        # Optimization Page (YENİ METİNLER EKLENDİ)
        "opt_title": "Takım Optimizasyonu",
        "opt_info": "Genetik Algoritma kullanarak, bütçeniz ve formasyonunuza en uygun takımı bulun.",
        "opt_params": "Optimizasyon Parametreleri",
        "opt_budget": "Bütçe (EUR)",
        "opt_formation": "Formasyon",
        "opt_ga_params": "Genetik Algoritma Parametreleri",
        "opt_generations": "Nesil Sayısı",
        "opt_generations_help": "Algoritma kaç kez evrimleşecek. Daha fazla nesil, daha iyi sonuç ama daha yavaş işlem demektir.",
        "opt_population": "Popülasyon Büyüklüğü",
        "opt_population_help": "Her nesilde kaç farklı takım denenecek. Daha fazla popülasyon, daha fazla çeşitlilik demektir.",
        "opt_advanced_options": "Gelişmiş Seçenekler",
        "opt_use_ml": "Makine Öğrenmesi Kullan",
        "opt_use_ml_help": "Oyuncu değerlerini tahmin ederek daha ekonomik ve potansiyelli oyuncuları seçmeye öncelik verir.",
        "opt_ml_model_not_found": "ML modeli bulunamadı. Lütfen önce bir model eğitin.",
        "opt_use_synergy": "Sinerji NN Kullan",
        "opt_use_synergy_help": "Takım uyumunu yapay zeka ile değerlendirerek daha dengeli ve kimyası yüksek bir kadro kurar.",
        "opt_synergy_model_not_found": "Sinerji modeli bulunamadı. Lütfen önce bir model eğitin.",
        "opt_button_start": "Optimizasyonu Başlat",
        "opt_spinner_optimizing": "Optimizasyon sürüyor... Bu işlem seçilen parametrelere göre birkaç dakika sürebilir.",
        "opt_status_generation": "Nesil {curr}/{total} - En İyi Fitness: {fit:.1f}",
        "opt_success_completed": "Optimizasyon tamamlandı!",
        "opt_error": "Optimizasyon sırasında bir hata oluştu: {e}",
        "opt_error_suggestion": "Öneri: Bütçeyi artırmayı veya farklı bir formasyon denemeyi düşünün.",
        "opt_results_title": "🏆 Optimal Takım Sonuçları",
        "opt_total_fitness": "Toplam Fitness Skoru",
        "opt_total_value": "Toplam Takım Değeri",
        "opt_avg_overall_squad": "Ortalama Overall",
        "opt_chemistry": "Kimya Skoru",
        "opt_squad_list": "İlk 11 Kadrosu",
        "opt_bench_list": "Yedek Oyuncular",
        "opt_button_save_squad": "Takımı CSV Olarak Kaydet",
        "opt_success_squad_saved": "Takım başarıyla kaydedildi: {path}",
    
        # About Page
        "about_title": "Hakkında",
        "about_subtitle": "Modern yapay zeka teknikleri kullanarak optimal futbol takımı oluşturma sistemi.",
        "about_features_title": "🚀 Özellikler",
        "about_features_list": "- **Veri Analizi**: 18,000+ oyuncu verisini interaktif grafiklerle keşfedin.\n- **Makine Öğrenmesi**: 3 farklı ML modeli ile oyuncu değeri tahmini.\n- **Neural Network**: Takım sinerjisini öğrenen 3 katmanlı yapay zeka.\n- **Genetik Algoritma**: Evrimsel optimizasyon ile en iyi takımı bulun.",
        "about_tech_title": "🛠️ Teknolojiler",
        "about_tech_list": "- **Python & Streamlit**: Uygulama iskeleti.\n- **Scikit-learn & XGBoost**: Makine öğrenmesi modelleri.\n- **Pandas & NumPy**: Veri işleme.\n- **Plotly**: İnteraktif görselleştirmeler.",

        # Placeholder texts for other pages
        "opt_title": "Takım Optimizasyonu",
        "about_title": "Hakkında",
    },
    'en': {
        # Sidebar & Main
        "app_title": "FC26 Squad Optimizer",
        "nav_title": "Navigation",
        "page_select": "Select Page:",
        "home": "Home",
        "data_analysis": "Data Analysis",
        "ml_training": "Machine Learning",
        "synergy_nn": "Synergy NN",
        "optimization": "Team Optimization",
        "about": "About",
        "data_status_loaded": "Data Loaded",
        "total_players": "Total Players",
        "avg_overall": "Avg. Overall",
        "data_status_unloaded": "Data not loaded",
        "load_data_button": "Load Data",
        "model_status": "Model Status",
        "ml_model": "ML Model",
        "synergy_model": "Synergy Model",
        "made_with": "Made with Streamlit",
        "version": "Version",
        "error_file_not_found": "ERROR: File not found at '{path}'!",
        "info_save_csv": "Please save your CSV file as '{path}'.",
        "spinner_loading_data": "Loading data...",
        "warning_load_data_first": "You need to load data first!",

        # Home Page
        "home_quick_start": "Quick Start",
        "home_start_prompt": "Start by clicking the **'Load Data'** button in the left menu!",
        "home_data_loaded_prompt": "Data loaded! Select a page from the left menu to continue.",
        "home_avg_value": "Average Value",
        "home_max_overall": "Highest Overall",
        "home_saved_models": "Saved Models",
        "home_models_found": "{count} trained models found.",
        "home_view_models": "View Models",
        "home_no_models": "No trained models yet.",
        "home_recent_squads": "Recent Squads",
        "home_squads_found": "{count} squad records found.",
        "home_view_squads": "View Squads",
        "home_no_squads": "No optimized squads yet.",

        # Data Analysis Page
        "da_title": "Data Analysis and Visualization",
        "da_filters": "Filters",
        "da_min_overall": "Minimum Overall",
        "da_max_value": "Max Value (EUR)",
        "da_position_filter": "Position Filter",
        "da_showing_players": "Showing {count} players (Total: {total})",
        "da_tab_distributions": "Distributions",
        "da_tab_value": "Value Analysis",
        "da_tab_nationality": "Nationality/League",
        "da_tab_player_list": "Player List",
        "da_chart_overall_dist": "Overall Distribution",
        "da_chart_age_dist": "Age Distribution",
        "da_chart_overall_vs_value": "Overall vs Value Relation",
        "da_chart_top_10_valuable": "Top 10 Most Valuable Players",
        "da_chart_top_15_nations": "Top 15 Nations by Player Count",
        "da_chart_top_10_leagues": "Top 10 Leagues by Player Count",
        "da_player_list_info": "Listing a total of {count} players matching the filter.",
        
        # ML Page
        "ml_title": "Machine Learning Model Training",
        "ml_info": "Machine learning models predict player values, helping you find undervalued players with high potential.",
        "ml_tab_train": "Train Model",
        "ml_tab_compare": "Model Comparison",
        "ml_tab_undervalued": "Undervalued Players",
        "ml_train_new": "Train New Model",
        "ml_model_features_title": "Model Features:",
        "ml_model_feature_1": "- Random Forest (100 trees)",
        "ml_model_feature_2": "- Gradient Boosting (100 trees)",
        "ml_model_feature_3": "- XGBoost (100 trees)",
        "ml_model_feature_4": "- R², MAE, RMSE metrics",
        "ml_model_feature_5": "- Best model is auto-selected",
        "ml_test_data_ratio": "Test Data Ratio",
        "ml_training_data": "Training Data",
        "ml_test_data": "Test Data",
        "ml_button_start_training": "Start Model Training",
        "ml_spinner_training": "Training models... This might take a few minutes.",
        "ml_success_trained": "Models trained successfully!",
        "ml_performance": "Model Performance",
        "ml_r2_score": "R² Score",
        "ml_mae": "MAE",
        "ml_rmse": "RMSE",
        "ml_button_save_model": "Save Model",
        "ml_success_saved": "Model saved to: {path}",
        "ml_error_training": "An error occurred during model training: {e}",
        "ml_info_train_first": "You need to train a model from the 'Train Model' tab first.",
        "ml_chart_r2_comparison": "R² Score Comparison",
        "ml_chart_mae_comparison": "MAE Comparison (Million EUR)",
        "ml_undervalued_threshold": "Undervalued Threshold",
        "ml_undervalued_help": "Ratio of model prediction to actual value. E.g., 0.5 = actual value is half of the prediction.",
        "ml_button_find_undervalued": "Find Undervalued Players",
        "ml_spinner_finding": "Analyzing...",
        "ml_undervalued_found": "Found {count} undervalued players!",
        "ml_undervalued_not_found": "No undervalued players found at the specified threshold. Try increasing it.",
        "ml_undervalued_info_showing": "Showing first 50 players. Total: {count}",
        "ml_undervalued_avg_overall": "Average Overall",
        "ml_undervalued_avg_age": "Average Age",
        "ml_undervalued_avg_potential": "Average Potential",
        "ml_undervalued_df_cols": {'short_name': 'Player', 'overall': 'OVR', 'potential': 'POT', 'age': 'Age', 'player_positions': 'Position', 'actual_value': 'Actual Value', 'predicted_value': 'Prediction', 'value_diff': 'Difference', 'value_ratio': 'Ratio', 'club_name': 'Club', 'league_name': 'League', 'nationality_name': 'Country'},
        "ml_hyperparameters": "Hyperparameter Tuning (Optional)",
        "ml_n_estimators": "Number of Trees",
        "ml_max_depth": "Max Depth (0 = Unlimited)",
        "ml_learning_rate": "Learning Rate",
        "ml_rf_settings": "Random Forest Settings",
        "ml_gb_settings": "Gradient Boosting Settings",
        "ml_xgb_settings": "XGBoost Settings",

        # Synergy Page
        "syn_title": "Synergy Neural Network Training",
        "syn_info": "The Synergy NN predicts how well 11 players will perform together, analyzing 28+ features like age balance, playstyle compatibility, and chemistry.",
        "syn_model_ready": "Synergy model is loaded and ready to use!",
        "syn_model_overwrite_info": "If you train a new model, it will overwrite the current one.",
        "syn_model_not_ready": "No trained synergy model found yet.",
        "syn_model_details_title": "Model Info:",
        "syn_model_detail_1": "- 3-layer Neural Network (NN)",
        "syn_model_detail_2": "- 128-64-32 neuron architecture",
        "syn_model_detail_3": "- Analyzes 28+ team features",
        "syn_model_detail_4": "- Outputs a synergy score (0-100)",
        "syn_tab_train": "Train Model",
        "syn_tab_test": "Test Model",
        "syn_train_new": "Train New Synergy NN",
        "syn_training_samples": "Number of Training Samples",
        "syn_samples_help": "More samples = better model but longer training time.",
        "syn_button_start_training": "Start Synergy NN Training",
        "syn_spinner_creating_predictor": "Creating synergy predictor...",
        "syn_spinner_training": "Generating {count} synthetic teams and training model...",
        "syn_spinner_saving": "Saving model...",
        "syn_success_trained": "Synergy NN trained and saved successfully!",
        "syn_model_saved_at": "Model saved to: {path}",
        "syn_training_results": "Training Results",
        "syn_train_mse": "Training MSE",
        "syn_test_mse": "Test MSE",
        "syn_train_r2": "Training R²",
        "syn_test_r2": "Test R²",
        "syn_perf_excellent": "Excellent model performance! The model learned very well.",
        "syn_perf_good": "Good model performance. The model is successful.",
        "syn_perf_fair": "Fair model performance. You could try training with more samples.",
        "syn_perf_poor": "Poor model performance. Consider reviewing parameters or sample count.",
        "syn_test_info": "Generate a random team to test the current synergy model.",
        "syn_test_formation": "Test Formation",
        "syn_button_test": "Generate Random Team & Test",
        "syn_test_results_title": "Test Team Results",
        "syn_test_score": "Synergy Score",
        "syn_test_avg_overall": "Avg. Overall",
        "syn_test_avg_age": "Avg. Age",
        "syn_test_total_value": "Total Value",
        "syn_test_squad_list": "Test Team Squad",
        "syn_error_not_enough_players": "Could not create a test team. The dataset might not have enough players.",
        "syn_hyperparameters": "Hyperparameter Tuning",
        "syn_hidden_layers": "Hidden Layer Structure (e.g., 128,64,32)",
        "syn_hidden_layers_help": "Enter neuron counts for each layer, separated by commas.",
        "syn_activation": "Activation Function",
        "syn_solver": "Solver (Optimizer)",
        "syn_max_iter": "Max Iterations (Epochs)",

       # Optimization Page (NEW TEXTS ADDED)
        "opt_title": "Team Optimization",
        "opt_info": "Find the best possible squad within your budget and formation using a Genetic Algorithm.",
        "opt_params": "Optimization Parameters",
        "opt_budget": "Budget (EUR)",
        "opt_formation": "Formation",
        "opt_ga_params": "Genetic Algorithm Parameters",
        "opt_generations": "Number of Generations",
        "opt_generations_help": "How many times the algorithm will evolve. More generations lead to better results but take longer.",
        "opt_population": "Population Size",
        "opt_population_help": "How many different squads are tested in each generation. A larger population means more diversity.",
        "opt_advanced_options": "Advanced Options",
        "opt_use_ml": "Use Machine Learning",
        "opt_use_ml_help": "Prioritizes more economical and high-potential players by predicting their market value.",
        "opt_ml_model_not_found": "ML model not found. Please train a model first.",
        "opt_use_synergy": "Use Synergy NN",
        "opt_use_synergy_help": "Builds a more balanced squad with higher chemistry by evaluating team synergy with AI.",
        "opt_synergy_model_not_found": "Synergy model not found. Please train a model first.",
        "opt_button_start": "Start Optimization",
        "opt_spinner_optimizing": "Optimization in progress... This may take a few minutes depending on the selected parameters.",
        "opt_status_generation": "Generation {curr}/{total} - Best Fitness: {fit:.1f}",
        "opt_success_completed": "Optimization completed successfully!",
        "opt_error": "An error occurred during optimization: {e}",
        "opt_error_suggestion": "Suggestion: Try increasing the budget or selecting a different formation.",
        "opt_results_title": "🏆 Optimal Squad Results",
        "opt_total_fitness": "Total Fitness Score",
        "opt_total_value": "Total Squad Value",
        "opt_avg_overall_squad": "Average Overall",
        "opt_chemistry": "Chemistry Score",
        "opt_squad_list": "Starting XI Squad",
        "opt_bench_list": "Substitutes",
        "opt_button_save_squad": "Save Squad as CSV",
        "opt_success_squad_saved": "Squad saved successfully to: {path}",

        # About Page
        "about_title": "About",
        "about_subtitle": "A system for creating optimal football squads using modern artificial intelligence techniques.",
        "about_features_title": "🚀 Features",
        "about_features_list": "- **Data Analysis**: Explore 18,000+ player data with interactive charts.\n- **Machine Learning**: Predict player value with 3 different ML models.\n- **Neural Network**: A 3-layer AI that learns team synergy.\n- **Genetic Algorithm**: Find the best team through evolutionary optimization.",
        "about_tech_title": "🛠️ Technologies",
        "about_tech_list": "- **Python & Streamlit**: Application framework.\n- **Scikit-learn & XGBoost**: Machine learning models.\n- **Pandas & NumPy**: Data manipulation.\n- **Plotly**: Interactive visualizations.",       
        
        # Placeholder texts for other pages
        "opt_title": "Team Optimization",
        "about_title": "About",
    }
}